// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZCfuERVUz36rmXdp0aKmxj0pXKQZGzY',
    appId: '1:14997023652:web:ebcb4c97fe5c687a62af31',
    messagingSenderId: '14997023652',
    projectId: 'cheesequiz-af7c2',
    authDomain: 'cheesequiz-af7c2.firebaseapp.com',
    storageBucket: 'cheesequiz-af7c2.firebasestorage.app',
    measurementId: 'G-HVB9JHFNKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvP9nQGRKOIfBxxt15gteD9gc7dzhMy4',
    appId: '1:14997023652:android:658de1f0aed95f3c62af31',
    messagingSenderId: '14997023652',
    projectId: 'cheesequiz-af7c2',
    storageBucket: 'cheesequiz-af7c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJP7AF5sli13ZxBsjSmLk5X8T2K9yPDI',
    appId: '1:14997023652:ios:a02df0d0b99c5b6a62af31',
    messagingSenderId: '14997023652',
    projectId: 'cheesequiz-af7c2',
    storageBucket: 'cheesequiz-af7c2.firebasestorage.app',
    iosBundleId: 'com.example.cheezQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJP7AF5sli13ZxBsjSmLk5X8T2K9yPDI',
    appId: '1:14997023652:ios:a02df0d0b99c5b6a62af31',
    messagingSenderId: '14997023652',
    projectId: 'cheesequiz-af7c2',
    storageBucket: 'cheesequiz-af7c2.firebasestorage.app',
    iosBundleId: 'com.example.cheezQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnZCfuERVUz36rmXdp0aKmxj0pXKQZGzY',
    appId: '1:14997023652:web:3eb6839d335a31ae62af31',
    messagingSenderId: '14997023652',
    projectId: 'cheesequiz-af7c2',
    authDomain: 'cheesequiz-af7c2.firebaseapp.com',
    storageBucket: 'cheesequiz-af7c2.firebasestorage.app',
    measurementId: 'G-SLXB2Y4R33',
  );
}
